CREATE TYPE "DrawMode" AS ENUM ('PRELIMINARIES', 'REPECHAGE');
ALTER TABLE "Tournament" ADD COLUMN "drawMode" "DrawMode" NOT NULL DEFAULT 'PRELIMINARIES';
ALTER TABLE "Team" ADD COLUMN "playerOne" TEXT;
ALTER TABLE "Team" ADD COLUMN "playerTwo" TEXT;
