import { NextResponse } from "next/server";
import { prisma } from "../../../lib/db";
import { requireAdmin } from "../../../lib/auth";
import { MAX_NAME_LENGTH } from "../../../lib/security";

function text(value: unknown, label: string) { const result = String(value || "").trim().replace(/\s+/g, " "); if (!result) throw Error(label + " obbligatorio"); if (result.length > MAX_NAME_LENGTH) throw Error(label + " troppo lungo"); return result; }
function errorResponse(error: any) { const message = error?.message || "Operazione non riuscita"; return NextResponse.json({ error: message }, { status: message === "NON_AUTORIZZATO" ? 401 : 400 }); }
export async function POST(request: Request) { try { const body = await request.json().catch(() => ({})); const tournament = await prisma.tournament.findFirst({ orderBy: { createdAt: "desc" } }); if (!tournament || tournament.status !== "SETUP") throw Error("Le iscrizioni non sono disponibili"); const playerOne = text(body.playerOne, "Primo giocatore"), playerTwo = text(body.playerTwo, "Secondo giocatore"); await prisma.registration.create({ data: { tournamentId: tournament.id, playerOne, playerTwo } }); return NextResponse.json({ ok: true }); } catch (error: any) { return errorResponse(error); } }
export async function GET() { try { const tournament = await prisma.tournament.findFirst({ orderBy: { createdAt: "desc" } }); if (!tournament) throw Error("Torneo non trovato"); await requireAdmin(tournament.id); const registrations = await prisma.registration.findMany({ where: { tournamentId: tournament.id }, orderBy: { createdAt: "asc" } }); return NextResponse.json(registrations); } catch (error: any) { return errorResponse(error); } }
export async function PATCH(request: Request) { try { const body = await request.json().catch(() => ({})); const tournament = await prisma.tournament.findFirst({ orderBy: { createdAt: "desc" } }); if (!tournament) throw Error("Torneo non trovato"); await requireAdmin(tournament.id); if (tournament.status !== "SETUP") throw Error("Le iscrizioni sono chiuse"); const registration = await prisma.registration.findFirst({ where: { id: String(body.id || ""), tournamentId: tournament.id, status: "PENDING" } }); if (!registration) throw Error("Richiesta non disponibile"); const action = String(body.action || ""); if (action === "approve") { await prisma.$transaction([prisma.team.create({ data: { tournamentId: tournament.id, playerOne: registration.playerOne, playerTwo: registration.playerTwo, name: registration.playerOne + " / " + registration.playerTwo } }), prisma.registration.update({ where: { id: registration.id }, data: { status: "APPROVED", reviewedAt: new Date() } })]); } else if (action === "reject") await prisma.registration.update({ where: { id: registration.id }, data: { status: "REJECTED", reviewedAt: new Date() } }); else throw Error("Azione non valida"); return NextResponse.json({ ok: true }); } catch (error: any) { return errorResponse(error); } }
